import os
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import A4

FILE_PATH = os.getenv("FILE_PATH", ".")

def create_file(file_id: int):
    pdf_path = os.path.join(FILE_PATH, f"{file_id}.pdf")

    c = canvas.Canvas(pdf_path, pagesize=A4)

    # ✅ 기본 폰트 (TTF 불필요)
    c.setFont("Helvetica", 12)

    c.drawString(100, 750, "Hello. This PDF is generated by ReportLab.")
    c.drawString(100, 730, "File ID : %d" % file_id)

    c.showPage()
    c.save()

    return pdf_path
